# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"

  # Salt master
  config.vm.define "master" do |node|
    node.vm.hostname = "master"
    node.vm.network :private_network, ip: "192.168.33.10"

    node.vm.synced_folder "../salt/", "/srv/salt"
    node.vm.synced_folder "../pillar/", "/srv/pillar"

    # salt-master provisioning
    node.vm.provision :salt do |salt|
      salt.install_master = true
      salt.no_minion = true
      salt.run_highstate = false
    end
  end

  # Salt minion01
  config.vm.define "ceph-node01" do |node|
    node.vm.hostname = "ceph-node01"
    node.vm.network :private_network, ip: "192.168.33.20"

    # Additional NIC for cluster network
    node.vm.network :private_network, ip: "192.168.36.20"

    # Add 2 additional 4GB drives
    node.vm.provider "virtualbox" do |v|
      ["1","2"].each do |disk|
        diskname = "../../ceph-node01-#{disk}.vdi"
        v.customize ['createhd', '--filename', diskname, '--size', 4096]
        v.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', disk, '--device', 0, '--type', 'hdd', '--medium', diskname]
      end
    end

    # salt-minion provisioning
    node.vm.provision :salt do |salt|
      salt.minion_config = "minion"
    end
  end

  # Salt minion02
  config.vm.define "ceph-node02" do |node|
    node.vm.hostname = "ceph-node02"
    node.vm.network :private_network, ip: "192.168.33.30"

    # Additional NIC for cluster network
    node.vm.network :private_network, ip: "192.168.36.30"

    # Add 2 additional 4GB drives
    node.vm.provider "virtualbox" do |v|
      ["1","2"].each do |disk|
        diskname = "../../ceph-node02-#{disk}.vdi"
        v.customize ['createhd', '--filename', diskname, '--size', 4096]
        v.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', disk, '--device', 0, '--type', 'hdd', '--medium', diskname]
      end
    end

    # salt-minion provisioning
    node.vm.provision :salt do |salt|
      salt.minion_config = "minion"
    end
  end
end
