# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "trusty64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
    
  # Salt master
  config.vm.define "master" do |node|
    node.vm.hostname = "master"
    node.vm.network :private_network, ip: "192.168.33.10"
    
    node.vm.synced_folder "../", "/srv/"
    
    # salt-master provisioning
    node.vm.provision :salt do |salt|
      salt.install_master = true
      salt.no_minion = true
      salt.run_highstate = false
    end
  end

  # Salt minion01
  config.vm.define "minion01" do |node|
    node.vm.hostname = "minion01"
    node.vm.network :private_network, ip: "192.168.33.20"
    
    # salt-minion provisioning
    node.vm.provision :salt do |salt|
      salt.minion_config = "minion"
    end  
  end

  # Salt minion02
  config.vm.define "minion02" do |node|
    node.vm.hostname = "minion02"
    node.vm.network :private_network, ip: "192.168.33.30"

    # salt-minion provisioning
    node.vm.provision :salt do |salt|
      salt.minion_config = "minion"
    end
  end
end
